"""Build driver (MSVC).

  python tools/build.py difftest   translate the CRT slice, build and run tests/difftest.c (x86)
  python tools/build.py host       translate everything, build the stand-in FFXiMain.dll and
                                   tests/boot.exe, and run the boot test (x86, R2)
  python tools/build.py boot64     the same translation built for a 64-bit host with the portable
                                   runtime (runtime/portable), and tests/boot64.exe run (x64, R3.1)

Needs generated/FFXiMain.unpacked.dll and generated/build.json (python tools/prepare.py), which
pick the retail build; its addresses go to generated/build.h. Incremental: the recompiler only
rewrites C files whose text changed, and only stale objects are recompiled.
"""
import json
import os
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, 'tools'))
import buildinfo  # noqa: E402

# The retail build tools/prepare.py chose (meta/builds.json); None before it has run.
BUILD = buildinfo.current(required=False)
META = BUILD and BUILD['ffximain_meta']  # per-build metadata (from the discovery pass)
IMAGE = os.path.join(ROOT, 'generated', 'FFXiMain.unpacked.dll')
RETAIL = os.path.join(ROOT, 'generated', 'FFXiMain.retail.dll')  # verified copy, written by prepare.py
BUILD_H = os.path.join(ROOT, 'generated', 'build.h')
SLICE = BUILD and ','.join(BUILD['crt'].values())  # the CRT functions tests/difftest.c compares
CFLAGS = ['/nologo', '/O2', '/MT', '/W3', '/std:c11', '/bigobj', '/I', 'runtime', '/I', 'runtime\\win32', '/I',
          'generated']
# 64-bit hosts: guest memory is a window (guest.h) and the runtime is runtime/portable
CFLAGS64 = ['/nologo', '/O2', '/MT', '/W3', '/std:c11', '/bigobj', '/DRT_GUEST_WINDOW', '/I', 'runtime', '/I',
            'runtime\\portable', '/I', 'generated']


def write_build_h():
    """generated/build.h: the addresses of this build that the runtime and tests name directly."""
    lines = ['/* Generated by tools/build.py from meta/builds.json. Do not edit. */', '#pragma once',
             '#define FFXI_BUILD "%s"' % BUILD['build'],
             '#define FFXI_VERSION "%s" /* the version string patch.ver carries */' % BUILD['version']]
    for k, v in BUILD['addresses'].items():
        lines.append('#define FFXI_%s 0x%08xu' % (k.upper(), int(v, 16)))
    for k, v in BUILD['crt'].items():
        a = int(v, 16)
        lines.append('#define CRT_%s 0x%08xu' % (k.upper(), a))
        lines.append('#define F_%s f_%08x' % (k.upper(), a))
    text = '\n'.join(lines) + '\n'
    try:
        with open(BUILD_H) as f:
            if f.read() == text:
                return
    except OSError:
        pass
    with open(BUILD_H, 'w') as f:
        f.write(text)


PORTABLE =['runtime\\runtime.c', 'runtime\\portable\\plat_win.c', 'runtime\\portable\\gwin.c',
            'runtime\\portable\\gthread.c', 'runtime\\portable\\thunk.c', 'runtime\\portable\\pe.c',
            'runtime\\portable\\k32.c', 'runtime\\portable\\polcore.c', 'runtime\\portable\\vfs.c',
            'runtime\\portable\\kobj.c', 'runtime\\portable\\k32_io.c', 'runtime\\portable\\polcore_slots.c',
            'runtime\\portable\\reg.c', 'runtime\\portable\\ole.c', 'runtime\\portable\\polcore_files.c',
            'runtime\\portable\\k32_misc.c', 'runtime\\portable\\polcore_polpro.c']


def msvc_env(arch='x86'):
    pf = os.environ.get('ProgramFiles(x86)', r'C:\Program Files (x86)')
    vswhere = os.path.join(pf, 'Microsoft Visual Studio', 'Installer', 'vswhere.exe')
    vs = subprocess.check_output([vswhere, '-latest', '-products', '*', '-property', 'installationPath'], text=True).strip()
    vcvars = os.path.join(vs, 'VC', 'Auxiliary', 'Build', 'vcvarsall.bat')
    env = dict(os.environ)
    env['PATH'] = os.path.dirname(vswhere) + ';' + env['PATH']
    out = subprocess.check_output('"%s" %s >nul && set' % (vcvars, arch), shell=True, text=True, env=env)
    for line in out.splitlines():
        if '=' in line:
            k, v = line.split('=', 1)
            env[k] = v
    return env


def run(cmd, env=None):
    print('>', ' '.join(cmd) if len(' '.join(cmd)) < 200 else ' '.join(cmd)[:200] + ' ...')
    if env is not None:
        # CreateProcess searches the parent's PATH, not env's: resolve cl/link against the VS PATH.
        exe = shutil.which(cmd[0], path=env['PATH'])
        if exe:
            cmd = [exe] + cmd[1:]
    if not os.path.isabs(cmd[0]) and os.path.exists(os.path.join(ROOT, cmd[0])):
        cmd = [os.path.join(ROOT, cmd[0])] + cmd[1:]  # relative programs are ours, under ROOT
    subprocess.check_call(cmd, cwd=ROOT, env=env)


def compile_stale(env, sources, objdir, extra, cflags=CFLAGS):
    os.makedirs(os.path.join(ROOT, objdir), exist_ok=True)
    stale = []
    for s in sources:
        obj = os.path.join(ROOT, objdir, os.path.splitext(os.path.basename(s))[0] + '.obj')
        src = os.path.join(ROOT, s)
        if not os.path.exists(obj) or os.path.getmtime(obj) < os.path.getmtime(src):
            stale.append(s)
        elif not s.startswith('generated') and os.path.getmtime(obj) < os.path.getmtime(BUILD_H):
            with open(src, errors='replace') as f:
                if '"build.h"' in f.read():  # another build's addresses
                    stale.append(s)
    if stale:
        print('compiling %d of %d' % (len(stale), len(sources)))
        run(['cl', '/c', '/MP'] + cflags + extra + stale + ['/Fo:%s\\' % objdir], env)
    return [os.path.join(objdir, os.path.splitext(os.path.basename(s))[0] + '.obj') for s in sources]


def recomp(out, extra):
    run([sys.executable, 'recomp/recomp.py', '--meta', META, '--image', IMAGE, '--retail', RETAIL, '--out', out] + extra)


def difftest(env):
    recomp('generated/slice', ['--functions', SLICE])
    gen = ['generated\\slice\\' + f for f in sorted(os.listdir(os.path.join(ROOT, 'generated', 'slice'))) if f.endswith('.c')]
    objs = compile_stale(env, gen + ['runtime\\runtime.c', 'tests\\difftest.c'], 'build\\slice', ['/I', 'generated\\slice'])
    run(['link', '/nologo', '/OUT:build\\difftest.exe', '/MACHINE:X86', '/DYNAMICBASE:NO', '/BASE:0x00400000'] + objs, env)
    run(['build\\difftest.exe'], env)


def host(env):
    recomp('generated/all', ['--all'])
    gen = ['generated\\all\\' + f for f in sorted(os.listdir(os.path.join(ROOT, 'generated', 'all'))) if f.endswith('.c')]
    objs = compile_stale(env, gen + ['runtime\\runtime.c', 'runtime\\win32\\bridge.c', 'runtime\\win32\\loader.c',
                                     'host\\ffximain.c'], 'build\\all', ['/I', 'generated\\all'])
    os.makedirs(os.path.join(ROOT, 'build', 'host'), exist_ok=True)
    # Fixed base, out of the way of the game image's preferred 0x10000000 (it may still be relocated).
    run(['link', '/nologo', '/DLL', '/DEF:host\\ffximain.def', '/OUT:build\\host\\FFXiMain.dll', '/MACHINE:X86',
         '/BASE:0x60000000', '/DYNAMICBASE:NO', 'ole32.lib', 'user32.lib', 'synchronization.lib'] + objs, env)
    boot = compile_stale(env, ['tests\\boot.c'], 'build\\boot', [])
    run(['link', '/nologo', '/OUT:build\\boot.exe', '/MACHINE:X86', 'ole32.lib', 'uuid.lib'] + boot, env)
    run(['build\\boot.exe', 'build\\host\\FFXiMain.dll', RETAIL], env)
    run(['build\\boot.exe', 'build\\host\\FFXiMain.dll', RETAIL, 'relocate'], env)  # as inside pol.exe


def boot64(env):
    recomp('generated/all', ['--all'])
    gen = ['generated\\all\\' + f for f in sorted(os.listdir(os.path.join(ROOT, 'generated', 'all'))) if f.endswith('.c')]
    objs = compile_stale(env, gen + PORTABLE + ['tests\\boot64.c'], 'build\\all64', ['/I', 'generated\\all'], CFLAGS64)
    run(['link', '/nologo', '/OUT:build\\boot64.exe', '/MACHINE:X64', 'synchronization.lib'] + objs, env)
    # the PlayOnline keys, as a Mac player would bring them (build/ is gitignored)
    reg = os.path.join(ROOT, 'build', 'playonline.reg')
    subprocess.call(['reg', 'export', r'HKLM\SOFTWARE\WOW6432Node\PlayOnlineUS', reg, '/y'], stdout=subprocess.DEVNULL)
    run(['build\\boot64.exe', RETAIL, BUILD['game']] + ([reg] if os.path.exists(reg) else []), env)


FFXI_META = BUILD and BUILD['ffxi_meta']
FFXI_IMAGE = os.path.join(ROOT, 'generated', 'FFXi.unpacked.dll')  # written by tools/prepare.py
FFXI_RETAIL = os.path.join(ROOT, 'generated', 'FFXi.retail.dll')
SDL3 = r'C:\Dev\SDL3\SDL3-3.4.16'
# mbedtls 3.x or 4.x built for x64 (the LandSandBoat sign-in's TLS, host\lsb_login.c)
MBEDTLS = r'C:\Dev\mbedtls'
MBEDTLS_LIBS = ['mbedtls.lib', 'mbedx509.lib', 'mbedcrypto.lib']


def host64(env):
    """The 64-bit game host: FFXiMain and FFXi.dll translated, the portable runtime, SDL3."""
    recomp('generated/all', ['--all'])
    run([sys.executable, 'recomp/recomp.py', '--meta', FFXI_META, '--image', FFXI_IMAGE, '--retail',
         FFXI_RETAIL, '--module', 'ffxi', '--out', 'generated/ffxi', '--all'])
    gen = ['generated\\all\\' + f for f in sorted(os.listdir(os.path.join(ROOT, 'generated', 'all'))) if f.endswith('.c')]
    gen_ffxi = ['generated\\ffxi\\' + f for f in sorted(os.listdir(os.path.join(ROOT, 'generated', 'ffxi'))) if f.endswith('.c')]
    objs = compile_stale(env, gen, 'build\\all64', ['/I', 'generated\\all'], CFLAGS64)
    objs += compile_stale(env, gen_ffxi, 'build\\ffxi64', ['/I', 'generated\\ffxi'], CFLAGS64)
    objs += compile_stale(env, PORTABLE + ['runtime\\portable\\user32.c', 'runtime\\portable\\d3d8.c', 'runtime\\portable\\dsound.c', 'runtime\\portable\\input.c', 'runtime\\portable\\dinput.c', 'runtime\\portable\\ws2.c', 'runtime\\portable\\gfx_null.c', 'host\\host64.c', 'host\\lsb_login.c'], 'build\\host64', ['/I', os.path.join(SDL3, 'include'), '/I', os.path.join(MBEDTLS, 'include')], CFLAGS64)
    run(['link', '/nologo', '/OUT:build\\host64.exe', '/MACHINE:X64', 'synchronization.lib', 'ws2_32.lib',
         os.path.join(SDL3, 'lib', 'x64', 'SDL3.lib'), 'advapi32.lib', 'bcrypt.lib']
        + [os.path.join(MBEDTLS, 'lib', l) for l in MBEDTLS_LIBS] + objs, env)
    shutil.copy(os.path.join(SDL3, 'lib', 'x64', 'SDL3.dll'), os.path.join(ROOT, 'build'))


def main():
    what = sys.argv[1] if len(sys.argv) > 1 else 'difftest'
    if BUILD is None:
        buildinfo.current()  # exits: run tools/prepare.py first
    env = msvc_env('x64' if what in ('boot64', 'host64') else 'x86')
    write_build_h()
    {'difftest': difftest, 'host': host, 'boot64': boot64, 'host64': host64}[what](env)


if __name__ == '__main__':
    main()
